name: Crypto Jet
on:
  workflow_dispatch:
jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: pip install requests matplotlib pillow
      - name: Run Crypto Jet
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: python bot.py
